import { MarketingShell } from "@/components/marketing/marketing-shell";

export const metadata = {
  title: "Privacy · Copper",
  description: "How Copper collects, uses, and protects your information.",
};

export default function PrivacyPage() {
  return (
    <MarketingShell
      title="Privacy Policy"
      subtitle="What we collect, why, and what we do with it."
      updated="May 2026"
    >
      <p className="text-base">
        This is a working draft of our privacy policy. We&apos;ll have it
        reviewed by counsel before we&apos;re open to the general public. If
        you have a question that isn&apos;t covered, email{" "}
        <a href="mailto:support@joincopper.io">support@joincopper.io</a>.
      </p>

      <h2>The short version</h2>
      <p>
        We collect what we need to run the AI receptionist on your behalf —
        your business details, your callers&apos; phone numbers and call
        transcripts, and your billing info. We don&apos;t sell your data. We
        don&apos;t share phone numbers with advertisers. We don&apos;t train
        AI models on your call transcripts.
      </p>

      <h2>What we collect</h2>
      <h3>From you, the business owner</h3>
      <p>
        Name, email, phone number, business name, hours, services, pricing,
        and anything else you put into onboarding or settings. Payment
        information is handled by Stripe — we never see your full card number.
      </p>
      <h3>From your callers and texters</h3>
      <p>
        Their phone number (from caller ID or the SMS header), the audio and
        transcript of their call, the text of their SMS messages, and any
        information they share during the conversation (name, address, the
        issue they&apos;re calling about).
      </p>
      <h3>From your use of the app</h3>
      <p>
        Standard things — IP address, browser type, pages visited. We use this
        to debug and improve the product.
      </p>

      <h2>SMS messaging</h2>
      <p>
        When you text a phone number associated with a business using Copper,
        your message and the business&apos;s reply are transmitted via SMS
        through our service. The reply may be generated by an AI assistant
        operating on the business&apos;s behalf or sent manually by the
        business owner.
      </p>
      <p>
        <strong>Consent.</strong> We don&apos;t send unsolicited SMS. Every
        outbound message is sent in direct response to an inbound text
        initiated by the consumer, or as an account notification to a
        business owner about activity on their own account. Business
        owners&apos; SMS notifications can be disabled in account settings at
        any time.
      </p>
      <p>
        <strong>Opt-out.</strong> Reply <code>STOP</code> to any text from a
        number operated through Copper to unsubscribe. Reply <code>HELP</code>{" "}
        for help. Reply <code>START</code> to re-subscribe after opting out.
        These commands are handled at the carrier level and take effect
        immediately.
      </p>
      <p>
        <strong>Carrier rates.</strong> Standard message and data rates from
        your mobile carrier may apply to messages you send to and receive
        from numbers operated through Copper. Message frequency varies based
        on the conversation.
      </p>
      <p>
        <strong>No resale of phone numbers.</strong> We never sell, rent, or
        share phone numbers with third parties for marketing purposes. Mobile
        opt-in data and consent records are not shared with third parties or
        affiliates for marketing or promotional purposes.
      </p>

      <h2>What we do with it</h2>
      <ul>
        <li>
          Run the AI receptionist: take calls, book appointments, send SMS,
          show you what happened in your dashboard.
        </li>
        <li>
          Send you notifications via SMS and email when something happens that
          you should know about.
        </li>
        <li>Bill you and handle support requests.</li>
        <li>Improve the product (in aggregate — never your individual data).</li>
      </ul>

      <h2>Who we share it with</h2>
      <p>
        We share data with the vendors we use to operate the service: Twilio
        (telephony and SMS), Vapi (voice AI), Resend (email), Stripe (billing),
        Supabase (database hosting), Vercel (web hosting), Cal.com (calendar
        booking), and OpenRouter (call summarization). Each is bound by their
        own privacy commitments.
      </p>
      <p>
        We don&apos;t sell your data. We don&apos;t share it with advertisers.
        We don&apos;t share phone numbers with anyone outside the vendors
        listed above.
      </p>

      <h2>How long we keep it</h2>
      <p>
        For as long as your account is active. If you cancel, we delete your
        call recordings, transcripts, and SMS conversations within 30 days
        and your account data within 90 days — unless we&apos;re required to
        retain something for legal or tax purposes.
      </p>

      <h2>Your rights</h2>
      <p>
        You can export your data or delete your account at any time by
        emailing <a href="mailto:support@joincopper.io">support@joincopper.io</a>.
        We&apos;ll respond within 7 days.
      </p>

      <h2>Changes to this policy</h2>
      <p>
        If we make material changes, we&apos;ll email you before they take
        effect.
      </p>
    </MarketingShell>
  );
}
